version: '3.8'

services:
  your-service-name:
    build:
    context: .
    dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: "production"
      MONGODB_URI: ${MONGODB_URI}
