version: '3.8'

services:
  your-service-name:
    image: maximotor-server
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: "production"
      MONGODB_URI: "mongodb+srv://ivnescbr1989:Xl1upkKpafKCKrqy@escobarcluster0.wfxgm0n.mongodb.net/?retryWrites=true&w=majority"
